// Destiny activity name + difficulty map, keyed by `referenceId` (the activity
// definition hash on each activity). Generated from the live Bungie manifest
// (DestinyActivityDefinition) — see scripts note in stats.js. Regenerate when new
// raids / dungeons / difficulties ship.
//
// difficulty is one of: normal | master | prestige | contest | grandmaster

export const ACTIVITY_MAP = {
    '43862588': { name: 'Pantheon: Morgeth', difficulty: 'normal', raw: 'Featured Encore: Morgeth: The Pantheon' },
    '107319834': { name: 'Crota\'s End', difficulty: 'normal', raw: 'Crota\'s End: Standard' },
    '119944200': { name: 'Leviathan, Spire of Stars', difficulty: 'normal', raw: 'Leviathan, Spire of Stars: Normal' },
    '124340010': { name: 'Ghosts of the Deep', difficulty: 'normal', raw: 'Ghosts of the Deep: Ultimatum' },
    '247869137': { name: 'Sundered Doctrine', difficulty: 'normal', raw: 'Sundered Doctrine' },
    '300092127': { name: 'Vesper\'s Host', difficulty: 'normal', raw: 'Vesper\'s Host: Normal' },
    '313828469': { name: 'Ghosts of the Deep', difficulty: 'normal', raw: 'Ghosts of the Deep: Standard' },
    '417231112': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '548750096': { name: 'Scourge of the Past', difficulty: 'normal', raw: 'Scourge of the Past' },
    '715153594': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy: Eternity' },
    // --- Rite of the Nine: Explorer / Matchmade variants (manifest 244019) ---
    '1788465402': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy: Explorer (Matchmade)' },
    '1225969316': { name: 'Spire of the Watcher', difficulty: 'normal', raw: 'Spire of the Watcher: Explorer' },
    '943878085': { name: 'Spire of the Watcher', difficulty: 'normal', raw: 'Spire of the Watcher: Explorer (Matchmade)' },
    '1094262727': { name: 'Ghosts of the Deep', difficulty: 'normal', raw: 'Ghosts of the Deep: Explorer' },
    '4190119662': { name: 'Ghosts of the Deep', difficulty: 'normal', raw: 'Ghosts of the Deep: Explorer (Matchmade)' },
    '3521648250': { name: 'Sundered Doctrine', difficulty: 'master', raw: 'Sundered Doctrine: Master' },
    '1801496203': { name: 'Spire of the Watcher', difficulty: 'master', raw: 'Spire of the Watcher: Master' },
    '785700673': { name: 'Pit of Heresy', difficulty: 'master', raw: 'Pit of Heresy: Master' },
    '785700678': { name: 'Pit of Heresy', difficulty: 'expert', raw: 'Pit of Heresy: Expert' },
    '2559374368': { name: 'Pit of Heresy', difficulty: 'legend', raw: 'Pit of Heresy: Legend' },
    '2559374374': { name: 'Pit of Heresy', difficulty: 'master', raw: 'Pit of Heresy: Master' },
    '2559374375': { name: 'Pit of Heresy', difficulty: 'master', raw: 'Pit of Heresy: Master' },
    '3012587626': { name: 'Duality', difficulty: 'master', raw: 'Duality: Master' },
    '1754635208': { name: 'Equilibrium', difficulty: 'contest', raw: 'Equilibrium: Contest' },
    '3492566689': { name: 'Vesper\'s Host', difficulty: 'normal', raw: 'Vesper\'s Host' },
    '4293676253': { name: 'Vesper\'s Host', difficulty: 'master', raw: 'Vesper\'s Host: Master' },
    '910380154': { name: 'Deep Stone Crypt', difficulty: 'normal', raw: 'Deep Stone Crypt' },
    '1042180643': { name: 'Garden of Salvation', difficulty: 'normal', raw: 'Garden of Salvation' },
    '1044919065': { name: 'The Desert Perpetual', difficulty: 'normal', raw: 'The Desert Perpetual: Standard' },
    '1077850348': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy' },
    '1112917203': { name: 'Grasp of Avarice', difficulty: 'master', raw: 'Grasp of Avarice: Master' },
    '1262462921': { name: 'Spire of the Watcher', difficulty: 'normal', raw: 'Spire of the Watcher: Standard' },
    '1374392663': { name: 'King\'s Fall', difficulty: 'normal', raw: 'King\'s Fall: Standard' },
    '1375089621': { name: 'Pit of Heresy', difficulty: 'normal', raw: 'Pit of Heresy: Normal' },
    '1441982566': { name: 'Vow of the Disciple', difficulty: 'normal', raw: 'Vow of the Disciple: Standard' },
    '1507509200': { name: 'Crota\'s End', difficulty: 'master', raw: 'Crota\'s End: Master' },
    '1516551982': { name: 'Pantheon: Calus Resplendent', difficulty: 'normal', raw: 'Pantheon: Calus Resplendent: Customize' },
    '1541433876': { name: 'Salvation\'s Edge', difficulty: 'normal', raw: 'Salvation\'s Edge: Standard' },
    '1668217731': { name: 'Duality', difficulty: 'master', raw: 'Duality: Master' },
    '1685065161': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '1915770060': { name: 'Vesper\'s Host', difficulty: 'normal', raw: 'Vesper\'s Host' },
    '2004855007': { name: 'Warlord\'s Ruin', difficulty: 'normal', raw: 'Warlord\'s Ruin: Standard' },
    '2032534090': { name: 'The Shattered Throne', difficulty: 'normal', raw: 'The Shattered Throne' },
    '2122313384': { name: 'Last Wish', difficulty: 'normal', raw: 'Last Wish: Standard' },
    '2296818662': { name: 'Spire of the Watcher', difficulty: 'master', raw: 'Spire of the Watcher: Master' },
    '2381413764': { name: 'Root of Nightmares', difficulty: 'normal', raw: 'Root of Nightmares: Standard' },
    '2530656885': { name: 'Pantheon: Morgeth Surpassing', difficulty: 'normal', raw: 'Pantheon: Morgeth Surpassing: Customize' },
    '2534833093': { name: 'Warlord\'s Ruin', difficulty: 'master', raw: 'Warlord\'s Ruin: Master' },
    '2582501063': { name: 'Pit of Heresy', difficulty: 'normal', raw: 'Pit of Heresy: Standard' },
    '2659723068': { name: 'Garden of Salvation', difficulty: 'normal', raw: 'Garden of Salvation' },
    '2693136600': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2693136601': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2693136602': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2693136603': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2693136604': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2693136605': { name: 'Leviathan', difficulty: 'normal', raw: 'Leviathan: Normal' },
    '2716998124': { name: 'Ghosts of the Deep', difficulty: 'master', raw: 'Ghosts of the Deep: Master' },
    '2727361621': { name: 'Equilibrium', difficulty: 'normal', raw: 'Equilibrium: Standard' },
    '2823159265': { name: 'Duality', difficulty: 'normal', raw: 'Duality: Standard' },
    '2918919505': { name: 'Root of Nightmares', difficulty: 'master', raw: 'Root of Nightmares: Master' },
    '2961030534': { name: 'Ghosts of the Deep', difficulty: 'normal', raw: 'Ghosts of the Deep: Eternity' },
    '3022541210': { name: 'Vault of Glass', difficulty: 'master', raw: 'Vault of Glass: Master' },
    '3089205900': { name: 'Leviathan, Eater of Worlds', difficulty: 'normal', raw: 'Leviathan, Eater of Worlds: Normal' },
    '3193125350': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy: Ultimatum' },
    '3257594522': { name: 'King\'s Fall', difficulty: 'master', raw: 'King\'s Fall: Master' },
    '3333172150': { name: 'Crown of Sorrow', difficulty: 'normal', raw: 'Crown of Sorrow: Normal' },
    '3339002067': { name: 'Spire of the Watcher', difficulty: 'normal', raw: 'Spire of the Watcher: Ultimatum' },
    '3458480158': { name: 'Garden of Salvation', difficulty: 'normal', raw: 'Garden of Salvation' },
    '3637651331': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy: Explorer' },
    '3774021532': { name: 'Grasp of Avarice', difficulty: 'master', raw: 'Grasp of Avarice: Master' },
    '3817322389': { name: 'The Desert Perpetual', difficulty: 'epic', raw: 'The Desert Perpetual: Epic' },
    '3834447244': { name: 'Sundered Doctrine', difficulty: 'normal', raw: 'Sundered Doctrine: Normal' },
    '3879860661': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '3881495763': { name: 'Vault of Glass', difficulty: 'normal', raw: 'Vault of Glass: Standard' },
    '3889634515': { name: 'Vow of the Disciple', difficulty: 'master', raw: 'Vow of the Disciple: Master' },
    '3896382790': { name: 'The Desert Perpetual', difficulty: 'contest', raw: 'The Desert Perpetual: Contest' },
    '4046934917': { name: 'Spire of the Watcher', difficulty: 'normal', raw: 'Spire of the Watcher: Eternity' },
    '4078656646': { name: 'Grasp of Avarice', difficulty: 'normal', raw: 'Grasp of Avarice: Standard' },
    '4129614942': { name: 'Salvation\'s Edge', difficulty: 'master', raw: 'Salvation\'s Edge: Master' },
    '4148187374': { name: 'Prophecy', difficulty: 'normal', raw: 'Prophecy' },
    '4169648176': { name: 'The Pantheon: Oryx Exalted', difficulty: 'normal', raw: 'The Pantheon: Oryx Exalted' },
    '4169648177': { name: 'The Pantheon: Rhulk Indomitable', difficulty: 'normal', raw: 'The Pantheon: Rhulk Indomitable' },
    '4169648179': { name: 'The Pantheon: Atraks Sovereign', difficulty: 'normal', raw: 'The Pantheon: Atraks Sovereign' },
    '4169648182': { name: 'The Pantheon: Nezarec Sublime', difficulty: 'normal', raw: 'The Pantheon: Nezarec Sublime' },
    '4179289725': { name: 'Crota\'s End', difficulty: 'normal', raw: 'Crota\'s End: Normal' },
    '747671496': { name: 'Pantheon: Insurrection Prime Revolutionary', difficulty: 'normal', raw: ' Insurrection Prime Revolutionary: Customize' },
    // --- Additional references resolved from the Bungie manifest ---
    // 321355645 is no longer in the live manifest (sunset); confirmed Spire of Stars: Prestige.
    '3213556450': { name: 'Leviathan, Spire of Stars', difficulty: 'prestige', raw: 'Leviathan, Spire of Stars: Prestige' },
    '757116822': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '809170886': { name: 'Leviathan, Eater of Worlds', difficulty: 'prestige', raw: 'Leviathan, Eater of Worlds: Prestige' },
    '1063970578': { name: 'King\'s Fall', difficulty: 'expert', raw: 'King\'s Fall: Expert' },
    '1681562271': { name: 'Vault of Glass', difficulty: 'master', raw: 'Vault of Glass: Master' },
    '2449714930': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '2964135793': { name: 'King\'s Fall', difficulty: 'master', raw: 'King\'s Fall: Master' },
    '3446541099': { name: 'Leviathan', difficulty: 'prestige', raw: 'Leviathan: Prestige' },
    '4217492330': { name: 'Vow of the Disciple', difficulty: 'master', raw: 'Vow of the Disciple: Master' },
}

// Look up a raid/dungeon activity by its referenceId. Falls back to a readable
// placeholder (keeping the raw hash visible) when an unmapped activity appears,
// e.g. a brand-new dungeon released after this map was generated.
export function describeActivity(referenceId, mode) {
    const hit = ACTIVITY_MAP[referenceId]
    if (hit) return hit
    const kind = mode === 'raid' ? 'Raid' : mode === 'dungeon' ? 'Dungeon' : 'Activity'
    return { name: `Unknown ${kind} (ref ${referenceId})`, difficulty: 'normal', raw: String(referenceId) }
}